In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('housing.csv')

In [4]:
df['income_cat'] = pd.cut(df['median_income'],bins=[0,1.5,3.0,4.5,6.0,np.inf],labels=[1,2,3,4,5])

In [5]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(df, df['income_cat']):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [6]:
for sett in (strat_train_set, strat_test_set):
    sett.drop('income_cat', axis=1, inplace=True)

In [7]:
df = strat_train_set.copy()

In [17]:
df

       longitude  latitude  ...  median_house_value  ocean_proximity
12655    -121.46     38.52  ...             72100.0           INLAND
15502    -117.23     33.09  ...            279600.0       NEAR OCEAN
2908     -119.04     35.37  ...             82700.0           INLAND
14053    -117.13     32.75  ...            112500.0       NEAR OCEAN
20496    -118.70     34.28  ...            238300.0        <1H OCEAN
...          ...       ...  ...                 ...              ...
15174    -117.07     33.03  ...            268500.0        <1H OCEAN
12661    -121.42     38.51  ...             90400.0           INLAND
19263    -122.72     38.44  ...            140400.0        <1H OCEAN
19140    -122.70     38.31  ...            258100.0        <1H OCEAN
19773    -122.14     39.97  ...             62700.0           INLAND

[16512 rows x 10 columns]

In [9]:
strat_train_set.drop('median_house_value', axis=1)
strat_labels = strat_train_set['median_house_value'].copy()

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median')
housing_num = df.select_dtypes(include=[np.number])
imputer.fit(housing_num)

ValueError: Cannot use median strategy with non-numeric data:
could not convert string to float: 'INLAND'

In [13]:
X=imputer.transform(housing_num)

In [14]:
housing = pd.DataFrame(X, columns=housing_num.columns, index=housing_num.index)

In [18]:
housing['ocean_proximity'] = df['ocean_proximity']

In [19]:
housing

       longitude  latitude  ...  median_house_value  ocean_proximity
12655    -121.46     38.52  ...             72100.0           INLAND
15502    -117.23     33.09  ...            279600.0       NEAR OCEAN
2908     -119.04     35.37  ...             82700.0           INLAND
14053    -117.13     32.75  ...            112500.0       NEAR OCEAN
20496    -118.70     34.28  ...            238300.0        <1H OCEAN
...          ...       ...  ...                 ...              ...
15174    -117.07     33.03  ...            268500.0        <1H OCEAN
12661    -121.42     38.51  ...             90400.0           INLAND
19263    -122.72     38.44  ...            140400.0        <1H OCEAN
19140    -122.70     38.31  ...            258100.0        <1H OCEAN
19773    -122.14     39.97  ...             62700.0           INLAND

[16512 rows x 10 columns]

In [20]:
set(housing['ocean_proximity'])

{'<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'}

In [25]:
# ordinary encoding
from sklearn.preprocessing import OrdinalEncoder

In [36]:
ordinal_encoder = OrdinalEncoder()
housing_cat = ordinal_encoder.fit_transform(housing)
housing_cat = pd.DataFrame(housing_cat, columns=housing.columns, index=housing_num.index)
housing_cat

       longitude  latitude  ...  median_house_value  ocean_proximity
12655      239.0     569.0  ...               292.0              1.0
15502      662.0      55.0  ...              2337.0              4.0
2908       481.0     273.0  ...               396.0              1.0
14053      672.0      21.0  ...               694.0              4.0
20496      515.0     174.0  ...              1942.0              0.0
...          ...       ...  ...                 ...              ...
15174      678.0      49.0  ...              2232.0              0.0
12661      243.0     568.0  ...               473.0              1.0
19263      113.0     561.0  ...               971.0              0.0
19140      115.0     548.0  ...              2133.0              0.0
19773      171.0     701.0  ...               200.0              1.0

[16512 rows x 10 columns]

In [ ]:
# one hot encoder
# fetching categorical data
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder()
housing_cat_1hot = one_hot_encoder.fit_transform(housing[['ocean_proximity']])

housing_cat_1hot.toarray()
housing_cat= pd.DataFrame(housing_cat_1hot.toarray(), columns=one_hot_encoder.get_feature_names_out(), index=housing_num.index)

In [40]:
housing_cat

       ocean_proximity_<1H OCEAN  ...  ocean_proximity_NEAR OCEAN
12655                        0.0  ...                         0.0
15502                        0.0  ...                         1.0
2908                         0.0  ...                         0.0
14053                        0.0  ...                         1.0
20496                        1.0  ...                         0.0
...                          ...  ...                         ...
15174                        1.0  ...                         0.0
12661                        0.0  ...                         0.0
19263                        1.0  ...                         0.0
19140                        1.0  ...                         0.0
19773                        0.0  ...                         0.0

[16512 rows x 5 columns]