In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('breast-cancer.csv')

In [5]:
df.head()

         id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0    842302         M  ...          0.4601                  0.11890
1    842517         M  ...          0.2750                  0.08902
2  84300903         M  ...          0.3613                  0.08758
3  84348301         M  ...          0.6638                  0.17300
4  84358402         M  ...          0.2364                  0.07678

[5 rows x 32 columns]

In [6]:
df.drop(columns='id',inplace=True)

In [7]:
df

    diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0           M        17.99  ...          0.4601                  0.11890
1           M        20.57  ...          0.2750                  0.08902
2           M        19.69  ...          0.3613                  0.08758
3           M        11.42  ...          0.6638                  0.17300
4           M        20.29  ...          0.2364                  0.07678
..        ...          ...  ...             ...                      ...
564         M        21.56  ...          0.2060                  0.07115
565         M        20.13  ...          0.2572                  0.06637
566         M        16.60  ...          0.2218                  0.07820
567         M        20.60  ...          0.4087                  0.12400
568         B         7.76  ...          0.2871                  0.07039

[569 rows x 31 columns]

In [8]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [10]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [12]:
X_train

array([[-1.26346127, -0.1720211 , -1.25170093, ..., -0.74579251,
         0.43928467,  0.07071029],
       [-0.51264012,  2.45120897, -0.58485324, ..., -1.75011135,
        -0.81848063, -0.90636253],
       [ 0.35557795,  0.723716  ,  0.31516089, ...,  0.12686258,
         0.44092881,  0.75537445],
       ...,
       [-0.15496889, -0.08061935, -0.13777645, ...,  0.47439365,
        -0.39593725, -0.38902414],
       [-0.01939996,  0.08618883, -0.01135586, ...,  1.04697787,
         0.44750536,  1.18219234],
       [-0.04247552, -0.59932425, -0.10135728, ..., -0.79753943,
        -0.37456346, -0.38244083]])

In [13]:
y_train

470    B
473    B
184    M
506    B
242    B
      ..
316    B
138    M
396    B
435    M
477    B
Name: diagnosis, Length: 455, dtype: object

In [14]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [15]:
y_test

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1])

In [16]:
y_train

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0])

Numpy array to pytorch tensors

In [17]:
import torch

In [18]:
X_train_tensor = torch.from_numpy(X_train)
y_train_tensor = torch.from_numpy(y_train)
X_test_tensor = torch.from_numpy(X_test)
y_test_tensor = torch.from_numpy(y_test)

In [20]:
X_train_tensor

tensor([[-1.2635, -0.1720, -1.2517,  ..., -0.7458,  0.4393,  0.0707],
        [-0.5126,  2.4512, -0.5849,  ..., -1.7501, -0.8185, -0.9064],
        [ 0.3556,  0.7237,  0.3152,  ...,  0.1269,  0.4409,  0.7554],
        ...,
        [-0.1550, -0.0806, -0.1378,  ...,  0.4744, -0.3959, -0.3890],
        [-0.0194,  0.0862, -0.0114,  ...,  1.0470,  0.4475,  1.1822],
        [-0.0425, -0.5993, -0.1014,  ..., -0.7975, -0.3746, -0.3824]],
       dtype=torch.float64)

Defining model

In [29]:
class mySimpleNN():
    
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)
        
    # defination of forword pass
    def forward(self,X):
        z = torch.mm(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    # binary cross entropy loss function
    def binary_cross_entropy(self,y_pred,y_true):
        # clmap prediction to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        loss= -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

In [66]:
learning_rate = 0.1
epochs= 10000

In [67]:
model = mySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
# take forword pass
    y_pred = model.forward(X_train_tensor)
# loss
    loss = model.binary_cross_entropy(y_pred,y_train_tensor)
# backword pass
    loss.backward()
    
# update parameter
    with torch.no_grad(): 
        model.weights.data -= learning_rate * model.weights.grad.data
        model.bias.data -= learning_rate * model.bias.grad.data

    model.weights.grad.data.zero_()
    model.bias.grad.data.zero_()

# print loss in each epoch
    print(f"epoch {epoch+1} loss: {loss.item()}")

epoch 1 loss: 3.691200997482071
epoch 2 loss: 3.5690638291604437
epoch 3 loss: 3.440721201229722
epoch 4 loss: 3.309041668153581
epoch 5 loss: 3.173868147703304
epoch 6 loss: 3.029295437784508
epoch 7 loss: 2.8803930728884897
epoch 8 loss: 2.7309855471034354
epoch 9 loss: 2.5762935081937135
epoch 10 loss: 2.41621909963467
epoch 11 loss: 2.254635249804179
epoch 12 loss: 2.0919732156447797
epoch 13 loss: 1.929555202895363
epoch 14 loss: 1.7691299453651022
epoch 15 loss: 1.617678247621884
epoch 16 loss: 1.473792928558941
epoch 17 loss: 1.341567317768687
epoch 18 loss: 1.2204709591240424
epoch 19 loss: 1.116053122368446
epoch 20 loss: 1.029190923326004
epoch 21 loss: 0.9597981641452776
epoch 22 loss: 0.9066701869204572
epoch 23 loss: 0.8675714562592205
epoch 24 loss: 0.8395835966031817
epoch 25 loss: 0.8196551014239488
epoch 26 loss: 0.8051470962293501
epoch 27 loss: 0.7941099202640618
epoch 28 loss: 0.7852556433587413
epoch 29 loss: 0.7777900200721948
epoch 30 loss: 0.7712411575263257
epoch 31 loss: 0.7653330892439477
epoch 32 loss: 0.7599043732479038
epoch 33 loss: 0.7548590776026688
epoch 34 loss: 0.7501382994872483
epoch 35 loss: 0.7457039486537198
epoch 36 loss: 0.7415296309733332
epoch 37 loss: 0.737595569469783
epoch 38 loss: 0.733885795146111
epoch 39 loss: 0.7303866032054992
epoch 40 loss: 0.7270857097989898
epoch 41 loss: 0.7239717940460931
epoch 42 loss: 0.7210342504973348
epoch 43 loss: 0.7182630556224637
epoch 44 loss: 0.7156486954181324
epoch 45 loss: 0.7131821252359923
epoch 46 loss: 0.7108547461163657
epoch 47 loss: 0.7086583891297618
epoch 48 loss: 0.706585303174897
epoch 49 loss: 0.7046281438433204
epoch 50 loss: 0.7027799621496171
epoch 51 loss: 0.7010341925834935
epoch 52 loss: 0.6993846403041396
epoch 53 loss: 0.6978254674968563
epoch 54 loss: 0.6963511790171277
epoch 55 loss: 0.694956607497016
epoch 56 loss: 0.6936368981052623
epoch 57 loss: 0.6923874931491185
epoch 58 loss: 0.6912041166910323
epoch 59 loss: 0.6900827593322372
epoch 60 loss: 0.6890196632916257
epoch 61 loss: 0.6880113078842804
epoch 62 loss: 0.6870543954812117
epoch 63 loss: 0.6861458380110385
epoch 64 loss: 0.685282744046001
epoch 65 loss: 0.6844624064989544
epoch 66 loss: 0.6836822909448185
epoch 67 loss: 0.6829400245691798
epoch 68 loss: 0.6822333857381206
epoch 69 loss: 0.6815602941766401
epoch 70 loss: 0.6809188017379388
epoch 71 loss: 0.6803070837421276
epoch 72 loss: 0.67972343086035
epoch 73 loss: 0.6791662415186592
epoch 74 loss: 0.678634014795094
epoch 75 loss: 0.6781253437830859
epoch 76 loss: 0.6776389093944758
epoch 77 loss: 0.6771734745759136
epoch 78 loss: 0.6767278789131613
epoch 79 loss: 0.6763010335987552
epoch 80 loss: 0.6758919167395426
epoch 81 loss: 0.6754995689817402
epoch 82 loss: 0.6751230894323438
epoch 83 loss: 0.6747616318569074
epoch 84 loss: 0.674414401134893
epoch 85 loss: 0.6740806499549507
epoch 86 loss: 0.6737596757336107
epoch 87 loss: 0.6734508177419473
epoch 88 loss: 0.6731534544258061
epoch 89 loss: 0.6728670009061576
epoch 90 loss: 0.6725909066470677
epoch 91 loss: 0.6723246532796393
epoch 92 loss: 0.672067752571098
epoch 93 loss: 0.6718197445289538
epoch 94 loss: 0.671580195630883
epoch 95 loss: 0.6713486971716405
epoch 96 loss: 0.6711248637189273
epoch 97 loss: 0.6709083316707157
epoch 98 loss: 0.6706987579070645
epoch 99 loss: 0.6704958185299575
epoch 100 loss: 0.6702992076851542
epoch 101 loss: 0.6701086364604683
epoch 102 loss: 0.6699238318552887
epoch 103 loss: 0.669744535816522
epoch 104 loss: 0.669570504336473
epoch 105 loss: 0.6694015066085011
epoch 106 loss: 0.6692373242365769
epoch 107 loss: 0.6690777504951376
epoch 108 loss: 0.6689225896358881
epoch 109 loss: 0.6687716562384315
epoch 110 loss: 0.6686247746018243
epoch 111 loss: 0.6684817781743578
epoch 112 loss: 0.6683425090190424
epoch 113 loss: 0.668206817312462
epoch 114 loss: 0.6680745608748059
epoch 115 loss: 0.6679456047290482
epoch 116 loss: 0.6678198206873788
epoch 117 loss: 0.6676970869631177
epoch 118 loss: 0.6675772878064644
epoch 119 loss: 0.6674603131625451
epoch 120 loss: 0.6673460583503242
epoch 121 loss: 0.6672344237610435
epoch 122 loss: 0.6671253145749363
epoch 123 loss: 0.6670186404950565
epoch 124 loss: 0.6669143154971305
epoch 125 loss: 0.6668122575944164
epoch 126 loss: 0.666712388616625
epoch 127 loss: 0.6666146340020094
epoch 128 loss: 0.6665189226018033
epoch 129 loss: 0.666425186496226
epoch 130 loss: 0.6663333608213354
epoch 131 loss: 0.6662433836060534
epoch 132 loss: 0.6661551956187256
epoch 133 loss: 0.6660687402226316
epoch 134 loss: 0.6659839632398867
epoch 135 loss: 0.6659008128232202
epoch 136 loss: 0.6658192393351465
epoch 137 loss: 0.6657391952340749
epoch 138 loss: 0.6656606349669334
epoch 139 loss: 0.6655835148679121
epoch 140 loss: 0.6655077930629523
epoch 141 loss: 0.6654334293796327
epoch 142 loss: 0.6653603852621299
epoch 143 loss: 0.6652886236909443
epoch 144 loss: 0.6652181091071071
epoch 145 loss: 0.6651488073405999
epoch 146 loss: 0.6650806855427366
epoch 147 loss: 0.6650137121222697
epoch 148 loss: 0.6649478566850018
epoch 149 loss: 0.6648830899766968
epoch 150 loss: 0.6648193838290918
epoch 151 loss: 0.664756711108833
epoch 152 loss: 0.6646950456691609
epoch 153 loss: 0.6646343623041866
epoch 154 loss: 0.6645746367056053
epoch 155 loss: 0.664515845421712
epoch 156 loss: 0.6644579658185802
epoch 157 loss: 0.6644009760432814
epoch 158 loss: 0.6643448549890311
epoch 159 loss: 0.6642895822621462
epoch 160 loss: 0.6642351381507163
epoch 161 loss: 0.6641815035948863
epoch 162 loss: 0.6641286601586632
epoch 163 loss: 0.66407659000316
epoch 164 loss: 0.6640252758611951
epoch 165 loss: 0.6639747010131745
epoch 166 loss: 0.6639248492641794
epoch 167 loss: 0.6638757049222022
epoch 168 loss: 0.6638272527774548
epoch 169 loss: 0.663779478082703
epoch 170 loss: 0.6637323665345605
epoch 171 loss: 0.6636859042556972
epoch 172 loss: 0.663640077777907
epoch 173 loss: 0.6635948740259937
epoch 174 loss: 0.6635502803024246
epoch 175 loss: 0.6635062842727166
epoch 176 loss: 0.6634628739515134
epoch 177 loss: 0.663420037689314
epoch 178 loss: 0.6633777641598241
epoch 179 loss: 0.6633360423478905
epoch 180 loss: 0.6632948615379957
epoch 181 loss: 0.663254211303275
epoch 182 loss: 0.6632140814950362
epoch 183 loss: 0.6631744622327512
epoch 184 loss: 0.6631353438944968
epoch 185 loss: 0.663096717107822
epoch 186 loss: 0.6630585727410195
epoch 187 loss: 0.66302090189478
epoch 188 loss: 0.6629836958942119
epoch 189 loss: 0.6629469462812055
epoch 190 loss: 0.6629106448071276
epoch 191 loss: 0.6628747834258261
epoch 192 loss: 0.6628393542869331
epoch 193 loss: 0.6628043497294482
epoch 194 loss: 0.6627697622755916
epoch 195 loss: 0.6627355846249108
epoch 196 loss: 0.662701809648631
epoch 197 loss: 0.6626684303842355
epoch 198 loss: 0.6626354400302655
epoch 199 loss: 0.6626028319413312
epoch 200 loss: 0.6625705996233194
epoch 201 loss: 0.6625387367287925
epoch 202 loss: 0.6625072370525681
epoch 203 loss: 0.6624760945274704
epoch 204 loss: 0.6624453032202473
epoch 205 loss: 0.6624148573276425
epoch 206 loss: 0.6623847511726181
epoch 207 loss: 0.6623549792007197
epoch 208 loss: 0.6623255359765775
epoch 209 loss: 0.662296416180538
epoch 210 loss: 0.6622676146054189
epoch 211 loss: 0.6622391261533828
epoch 212 loss: 0.6622109458329248
epoch 213 loss: 0.6621830687559682
epoch 214 loss: 0.6621554901350634
epoch 215 loss: 0.662128205280686
epoch 216 loss: 0.6621012095986293
epoch 217 loss: 0.6620744985874885
epoch 218 loss: 0.6620480678362302
epoch 219 loss: 0.6620219130218462
epoch 220 loss: 0.6619960299070866
epoch 221 loss: 0.6619704143382675
epoch 222 loss: 0.6619450622431553
epoch 223 loss: 0.6619199696289166
epoch 224 loss: 0.661895132580139
epoch 225 loss: 0.6618705472569137
epoch 226 loss: 0.6618462098929818
epoch 227 loss: 0.6618221167939377
epoch 228 loss: 0.6617982643354917
epoch 229 loss: 0.6617746489617857
epoch 230 loss: 0.661751267183762
epoch 231 loss: 0.6617281155775814
epoch 232 loss: 0.6617051907830923
epoch 233 loss: 0.6616824895023435
epoch 234 loss: 0.6616600084981429
epoch 235 loss: 0.6616377445926602
epoch 236 loss: 0.6616156946660697
epoch 237 loss: 0.6615938556552338
epoch 238 loss: 0.6615722245524238
epoch 239 loss: 0.6615507984040802
epoch 240 loss: 0.6615295743096044
epoch 241 loss: 0.6615085494201892
epoch 242 loss: 0.6614877209376802
epoch 243 loss: 0.661467086113468
epoch 244 loss: 0.6614466422474136
epoch 245 loss: 0.6614263866868018
epoch 246 loss: 0.6614063168253231
epoch 247 loss: 0.6613864301020855
epoch 248 loss: 0.6613667240006492
epoch 249 loss: 0.6613471960480906
epoch 250 loss: 0.6613278438140885
epoch 251 loss: 0.6613086649100364
epoch 252 loss: 0.6612896569881765
epoch 253 loss: 0.6612708177407578
epoch 254 loss: 0.6612521448992129
epoch 255 loss: 0.6612336362333594
epoch 256 loss: 0.6612152895506196
epoch 257 loss: 0.6611971026952596
epoch 258 loss: 0.6611790735476488
epoch 259 loss: 0.6611612000235364
epoch 260 loss: 0.6611434800733469
epoch 261 loss: 0.6611259116814916
epoch 262 loss: 0.6611084928656985
epoch 263 loss: 0.6610912216763571
epoch 264 loss: 0.6610740961958793
epoch 265 loss: 0.6610571145380753
epoch 266 loss: 0.6610402748475449
epoch 267 loss: 0.6610235752990833
epoch 268 loss: 0.6610070140970993
epoch 269 loss: 0.6609905894750486
epoch 270 loss: 0.6609742996948803
epoch 271 loss: 0.6609581430464939
epoch 272 loss: 0.6609421178472119
epoch 273 loss: 0.6609262224412621
epoch 274 loss: 0.6609104551992719
epoch 275 loss: 0.6608948145177747
epoch 276 loss: 0.6608792988187271
epoch 277 loss: 0.6608639065490364
epoch 278 loss: 0.6608486361800986
epoch 279 loss: 0.6608334862073468
epoch 280 loss: 0.66081845514981
epoch 281 loss: 0.6608035415496797
epoch 282 loss: 0.6607887439718879
epoch 283 loss: 0.6607740610036928
epoch 284 loss: 0.6607594912542746
epoch 285 loss: 0.660745033354338
epoch 286 loss: 0.660730685955725
epoch 287 loss: 0.6607164477310353
epoch 288 loss: 0.6607023173732539
epoch 289 loss: 0.6606882935953876
epoch 290 loss: 0.6606743751301077
epoch 291 loss: 0.6606605607294024
epoch 292 loss: 0.6606468491642331
epoch 293 loss: 0.6606332392242008
epoch 294 loss: 0.6606197297172174
epoch 295 loss: 0.6606063194691848
epoch 296 loss: 0.6605930073236791
epoch 297 loss: 0.660579792141643
epoch 298 loss: 0.6605666728010832
epoch 299 loss: 0.6605536481967739
epoch 300 loss: 0.660540717239966
epoch 301 loss: 0.6605278788581037
epoch 302 loss: 0.6605151319945443
epoch 303 loss: 0.6605024756082848
epoch 304 loss: 0.6604899086736946
epoch 305 loss: 0.6604774301802516
epoch 306 loss: 0.6604650391322849
epoch 307 loss: 0.6604527345487218
epoch 308 loss: 0.6604405154628404
epoch 309 loss: 0.6604283809220255
epoch 310 loss: 0.6604163299875307
epoch 311 loss: 0.6604043617342453
epoch 312 loss: 0.6603924752504633
epoch 313 loss: 0.6603806696376593
epoch 314 loss: 0.6603689440102674
epoch 315 loss: 0.6603572974954651
epoch 316 loss: 0.6603457292329596
epoch 317 loss: 0.660334238374781
epoch 318 loss: 0.6603228240850757
epoch 319 loss: 0.6603114855399066
epoch 320 loss: 0.6603002219270566
epoch 321 loss: 0.6602890324458339
epoch 322 loss: 0.6602779163068832
epoch 323 loss: 0.6602668727319981
epoch 324 loss: 0.6602559009539399
epoch 325 loss: 0.6602450002162569
epoch 326 loss: 0.6602341697731081
epoch 327 loss: 0.6602234088890909
epoch 328 loss: 0.6602127168390707
epoch 329 loss: 0.6602020929080138
epoch 330 loss: 0.6601915363908246
epoch 331 loss: 0.6601810465921842
epoch 332 loss: 0.6601706228263919
epoch 333 loss: 0.6601602644172117
epoch 334 loss: 0.6601499706977182
epoch 335 loss: 0.6601397410101485
epoch 336 loss: 0.6601295747057547
epoch 337 loss: 0.6601194711446595
epoch 338 loss: 0.660109429695715
epoch 339 loss: 0.6600994497363629
epoch 340 loss: 0.6600895306524992
epoch 341 loss: 0.6600796718383373
epoch 342 loss: 0.6600698726962789
epoch 343 loss: 0.6600601326367828
epoch 344 loss: 0.6600504510782377
epoch 345 loss: 0.6600408274468381
epoch 346 loss: 0.6600312611764599
epoch 347 loss: 0.6600217517085412
epoch 348 loss: 0.660012298491962
epoch 349 loss: 0.6600029009829294
epoch 350 loss: 0.6599935586448618
epoch 351 loss: 0.6599842709482767
epoch 352 loss: 0.6599750373706806
epoch 353 loss: 0.6599658573964592
epoch 354 loss: 0.6599567305167714
epoch 355 loss: 0.6599476562294441
epoch 356 loss: 0.659938634038869
epoch 357 loss: 0.659929663455901
epoch 358 loss: 0.6599207439977592
epoch 359 loss: 0.6599118751879279
epoch 360 loss: 0.6599030565560611
epoch 361 loss: 0.659894287637887
epoch 362 loss: 0.6598855679751163
epoch 363 loss: 0.6598768971153494
epoch 364 loss: 0.6598682746119868
epoch 365 loss: 0.6598597000241414
epoch 366 loss: 0.6598511729165506
epoch 367 loss: 0.6598426928594912
epoch 368 loss: 0.659834259428696
epoch 369 loss: 0.6598258722052702
epoch 370 loss: 0.6598175307756107
epoch 371 loss: 0.6598092347313265
epoch 372 loss: 0.6598009836691596
epoch 373 loss: 0.659792777190908
epoch 374 loss: 0.6597846149033503
epoch 375 loss: 0.6597764964181704
epoch 376 loss: 0.6597684213518841
epoch 377 loss: 0.659760389325767
epoch 378 loss: 0.6597523999657844
epoch 379 loss: 0.6597444529025196
epoch 380 loss: 0.659736547771107
epoch 381 loss: 0.6597286842111638
epoch 382 loss: 0.6597208618667234
epoch 383 loss: 0.6597130803861707
epoch 384 loss: 0.659705339422177
epoch 385 loss: 0.6596976386316378
epoch 386 loss: 0.6596899776756094
epoch 387 loss: 0.6596823562192493
epoch 388 loss: 0.6596747739317546
epoch 389 loss: 0.6596672304863037
epoch 390 loss: 0.6596597255599976
epoch 391 loss: 0.6596522588338031
epoch 392 loss: 0.6596448299924962
epoch 393 loss: 0.6596374387246068
epoch 394 loss: 0.6596300847223638
epoch 395 loss: 0.6596227676816426
epoch 396 loss: 0.6596154873019102
epoch 397 loss: 0.6596082432861758
epoch 398 loss: 0.6596010353409384
epoch 399 loss: 0.6595938631761358
epoch 400 loss: 0.6595867265050971
epoch 401 loss: 0.6595796250444923
epoch 402 loss: 0.6595725585142852
epoch 403 loss: 0.6595655266376867
epoch 404 loss: 0.6595585291411074
epoch 405 loss: 0.6595515657541128
epoch 406 loss: 0.6595446362093778
epoch 407 loss: 0.6595377402426433
epoch 408 loss: 0.6595308775926725
epoch 409 loss: 0.6595240480012069
epoch 410 loss: 0.6595172512129265
epoch 411 loss: 0.659510486975406
epoch 412 loss: 0.6595037550390762
epoch 413 loss: 0.6594970551571818
epoch 414 loss: 0.6594903870857434
epoch 415 loss: 0.659483750583518
epoch 416 loss: 0.6594771454119609
epoch 417 loss: 0.6594705713351879
epoch 418 loss: 0.6594640281199383
epoch 419 loss: 0.6594575155355386
epoch 420 loss: 0.6594510333538659
epoch 421 loss: 0.6594445813493138
epoch 422 loss: 0.6594381592987563
epoch 423 loss: 0.6594317669815137
epoch 424 loss: 0.6594254041793207
epoch 425 loss: 0.6594190706762899
epoch 426 loss: 0.6594127662588822
epoch 427 loss: 0.6594064907158728
epoch 428 loss: 0.6594002438383204
epoch 429 loss: 0.6593940254195353
epoch 430 loss: 0.6593878352550496
epoch 431 loss: 0.659381673142586
epoch 432 loss: 0.6593755388820287
epoch 433 loss: 0.6593694322753936
epoch 434 loss: 0.6593633531268002
epoch 435 loss: 0.6593573012424419
epoch 436 loss: 0.6593512764305597
epoch 437 loss: 0.6593452785014132
epoch 438 loss: 0.6593393072672539
epoch 439 loss: 0.659333362542299
epoch 440 loss: 0.6593274441427045
epoch 441 loss: 0.6593215518865397
epoch 442 loss: 0.6593156855937609
epoch 443 loss: 0.6593098450861874
epoch 444 loss: 0.6593040301874759
epoch 445 loss: 0.6592982407230966
epoch 446 loss: 0.6592924765203089
epoch 447 loss: 0.6592867374081379
epoch 448 loss: 0.6592810232173512
epoch 449 loss: 0.6592753337804358
epoch 450 loss: 0.6592696689315757
epoch 451 loss: 0.6592640285066292
epoch 452 loss: 0.6592584123431079
epoch 453 loss: 0.659252820280154
epoch 454 loss: 0.65924725215852
epoch 455 loss: 0.659241707820547
epoch 456 loss: 0.659236187110145
epoch 457 loss: 0.6592306898727713
epoch 458 loss: 0.6592252159554118
epoch 459 loss: 0.6592197652065604
epoch 460 loss: 0.6592143374761995
epoch 461 loss: 0.6592089326157822
epoch 462 loss: 0.6592035504782113
epoch 463 loss: 0.659198190917823
epoch 464 loss: 0.6591928537903663
epoch 465 loss: 0.6591875389529872
epoch 466 loss: 0.6591822462642094
epoch 467 loss: 0.6591769755839173
epoch 468 loss: 0.6591717267733389
epoch 469 loss: 0.6591664996950287
epoch 470 loss: 0.6591612942128505
epoch 471 loss: 0.6591561101919622
epoch 472 loss: 0.6591509474987972
epoch 473 loss: 0.6591458060010517
epoch 474 loss: 0.6591406855676654
epoch 475 loss: 0.6591355860688086
epoch 476 loss: 0.6591305073758655
epoch 477 loss: 0.6591254493614199
epoch 478 loss: 0.6591204118992392
epoch 479 loss: 0.6591153948642611
epoch 480 loss: 0.6591103981325777
epoch 481 loss: 0.6591054215814228
epoch 482 loss: 0.6591004650891568
epoch 483 loss: 0.6590955285352529
epoch 484 loss: 0.6590906118002839
epoch 485 loss: 0.6590857147659086
epoch 486 loss: 0.6590808373148583
epoch 487 loss: 0.6590759793309241
epoch 488 loss: 0.6590711406989437
epoch 489 loss: 0.6590663213047888
epoch 490 loss: 0.6590615210353531
epoch 491 loss: 0.6590567397785388
epoch 492 loss: 0.6590519774232461
epoch 493 loss: 0.659047233859359
epoch 494 loss: 0.6590425089777362
epoch 495 loss: 0.659037802670197
epoch 496 loss: 0.6590331148295107
epoch 497 loss: 0.6590284453493865
epoch 498 loss: 0.6590237941244603
epoch 499 loss: 0.659019161050285
epoch 500 loss: 0.6590145460233191
epoch 501 loss: 0.6590099489409165
epoch 502 loss: 0.6590053697013153
epoch 503 loss: 0.6590008082036282
epoch 504 loss: 0.6589962643478313
epoch 505 loss: 0.6589917380347549
epoch 506 loss: 0.6589872291660729
epoch 507 loss: 0.658982737644293
epoch 508 loss: 0.6589782633727481
epoch 509 loss: 0.6589738062555848
epoch 510 loss: 0.6589693661977554
epoch 511 loss: 0.6589649431050085
epoch 512 loss: 0.658960536883879
epoch 513 loss: 0.6589561474416803
epoch 514 loss: 0.6589517746864941
epoch 515 loss: 0.6589474185271624
epoch 516 loss: 0.6589430788732787
epoch 517 loss: 0.6589387556351796
epoch 518 loss: 0.6589344487239354
epoch 519 loss: 0.6589301580513436
epoch 520 loss: 0.6589258835299184
epoch 521 loss: 0.6589216250728849
epoch 522 loss: 0.6589173825941695
epoch 523 loss: 0.6589131560083924
epoch 524 loss: 0.6589089452308605
epoch 525 loss: 0.6589047501775588
epoch 526 loss: 0.6589005707651435
epoch 527 loss: 0.658896406910934
epoch 528 loss: 0.6588922585329062
epoch 529 loss: 0.6588881255496847
epoch 530 loss: 0.6588840078805359
epoch 531 loss: 0.6588799054453609
epoch 532 loss: 0.658875818164688
epoch 533 loss: 0.6588717459596674
epoch 534 loss: 0.6588676887520619
epoch 535 loss: 0.6588636464642428
epoch 536 loss: 0.6588596190191814
epoch 537 loss: 0.6588556063404439
epoch 538 loss: 0.6588516083521837
epoch 539 loss: 0.6588476249791354
epoch 540 loss: 0.6588436561466096
epoch 541 loss: 0.6588397017804855
epoch 542 loss: 0.6588357618072048
epoch 543 loss: 0.6588318361537666
epoch 544 loss: 0.6588279247477208
epoch 545 loss: 0.6588240275171622
epoch 546 loss: 0.6588201443907252
epoch 547 loss: 0.658816275297577
epoch 548 loss: 0.6588124201674139
epoch 549 loss: 0.658808578930454
epoch 550 loss: 0.658804751517432
epoch 551 loss: 0.6588009378595947
epoch 552 loss: 0.6587971378886947
epoch 553 loss: 0.6587933515369849
epoch 554 loss: 0.6587895787372152
epoch 555 loss: 0.6587858194226252
epoch 556 loss: 0.6587820735269396
epoch 557 loss: 0.658778340984364
epoch 558 loss: 0.6587746217295796
epoch 559 loss: 0.6587709156977379
epoch 560 loss: 0.6587672228244562
epoch 561 loss: 0.6587635430458131
epoch 562 loss: 0.658759876298343
epoch 563 loss: 0.6587562225190327
epoch 564 loss: 0.6587525816453155
epoch 565 loss: 0.6587489536150674
epoch 566 loss: 0.6587453383666028
epoch 567 loss: 0.6587417358386697
epoch 568 loss: 0.6587381459704452
epoch 569 loss: 0.6587345687015322
epoch 570 loss: 0.6587310039719534
epoch 571 loss: 0.6587274517221491
epoch 572 loss: 0.6587239118929714
epoch 573 loss: 0.6587203844256813
epoch 574 loss: 0.6587168692619438
epoch 575 loss: 0.6587133663438248
epoch 576 loss: 0.6587098756137861

In [62]:
model.bias

tensor([-0.4916], dtype=torch.float64, requires_grad=True)

In [63]:
# evaluation
with torch.no_grad():
    y_pred_test = model.forward(X_test_tensor)
    y_pred_test = (y_pred_test > 0.5).float()
    accuracy = (y_pred_test.squeeze() == y_test_tensor).float().mean()
    print(f"Test Accuracy: {accuracy.item() * 100:.2f}%")

Test Accuracy: 62.28%