In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
ft = pd.read_csv('flights_cleaned.csv')

In [13]:
ft

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Price
0,Jet Airways,2019-01-03,Banglore,New Delhi,BLR → BOM → DEL,11:40,785,1 stop,26890
1,SpiceJet,2019-01-03,Banglore,New Delhi,BLR → HYD → DEL,15:35,485,1 stop,7744
2,Jet Airways,2019-01-03,Banglore,New Delhi,BLR → BOM → DEL,08:00,740,1 stop,27992
3,Air India,2019-01-03,Banglore,New Delhi,BLR → BOM → AMD → DEL,08:50,2345,2 stops,17135
4,Jet Airways,2019-01-03,Banglore,New Delhi,BLR → BOM → DEL,11:40,1425,1 stop,25735
...,...,...,...,...,...,...,...,...,...
10678,Multiple carriers,2019-12-06,Delhi,Cochin,DEL → BOM → COK,09:15,585,1 stop,11622
10679,IndiGo,2019-12-06,Kolkata,Banglore,CCU → MAA → BLR,08:10,290,1 stop,5069
10680,Jet Airways,2019-12-06,Delhi,Cochin,DEL → BOM → COK,22:50,1210,1 stop,14714
10681,Air Asia,2019-12-06,Kolkata,Banglore,CCU → DEL → BLR,07:35,955,1 stop,5192
10682,Jet Airways,2019-12-06,Delhi,Cochin,DEL → BOM → COK,21:50,395,1 stop,10262

In [14]:
ft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Duration         10683 non-null  int64
 7   Total_Stops      10682 non-null  object
 8   Price            10683 non-null  int64
dtypes: int64(2), object(7)
memory usage: 751.3+ KB

In [16]:
ft[ft['Route'].isna()]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Price
6451,Air India,2019-06-05,Delhi,Cochin,NaN,09:45,1420,NaN,7480

In [17]:
ft['Route']=ft['Route'].fillna('DEL → BOM → COK	')

In [18]:
ft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10683 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Duration         10683 non-null  int64
 7   Total_Stops      10682 non-null  object
 8   Price            10683 non-null  int64
dtypes: int64(2), object(7)
memory usage: 751.3+ KB

In [19]:
ft

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Price
0,Jet Airways,2019-01-03,Banglore,New Delhi,BLR → BOM → DEL,11:40,785,1 stop,26890
1,SpiceJet,2019-01-03,Banglore,New Delhi,BLR → HYD → DEL,15:35,485,1 stop,7744
2,Jet Airways,2019-01-03,Banglore,New Delhi,BLR → BOM → DEL,08:00,740,1 stop,27992
3,Air India,2019-01-03,Banglore,New Delhi,BLR → BOM → AMD → DEL,08:50,2345,2 stops,17135
4,Jet Airways,2019-01-03,Banglore,New Delhi,BLR → BOM → DEL,11:40,1425,1 stop,25735
...,...,...,...,...,...,...,...,...,...
10678,Multiple carriers,2019-12-06,Delhi,Cochin,DEL → BOM → COK,09:15,585,1 stop,11622
10679,IndiGo,2019-12-06,Kolkata,Banglore,CCU → MAA → BLR,08:10,290,1 stop,5069
10680,Jet Airways,2019-12-06,Delhi,Cochin,DEL → BOM → COK,22:50,1210,1 stop,14714
10681,Air Asia,2019-12-06,Kolkata,Banglore,CCU → DEL → BLR,07:35,955,1 stop,5192
10682,Jet Airways,2019-12-06,Delhi,Cochin,DEL → BOM → COK,21:50,395,1 stop,10262

In [20]:
ft[[ft['Source'] == 'Chennai'][ft['Destination'] == 'Delhi']]

TypeError: list indices must be integers or slices, not Series

In [21]:
ft[(ft['Source'] == 'Mumbai')]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Price
14,IndiGo,2019-01-03,Mumbai,Hyderabad,BOM → HYD,16:55,90,non-stop,8853
26,Air India,2019-01-03,Mumbai,Hyderabad,BOM → HYD,13:55,90,non-stop,10082
95,IndiGo,2019-01-03,Mumbai,Hyderabad,BOM → HYD,02:30,90,non-stop,16000
120,Jet Airways,2019-01-03,Mumbai,Hyderabad,BOM → HYD,07:10,85,non-stop,17501
125,IndiGo,2019-01-03,Mumbai,Hyderabad,BOM → HYD,06:20,85,non-stop,17501
...,...,...,...,...,...,...,...,...,...
10530,Air India,2019-12-06,Mumbai,Hyderabad,BOM → HYD,13:55,90,non-stop,3100
10599,Air India,2019-12-06,Mumbai,Hyderabad,BOM → HYD,21:05,80,non-stop,3100
10635,Air India,2019-12-06,Mumbai,Hyderabad,BOM → HYD,19:30,75,non-stop,3100
10636,Jet Airways,2019-12-06,Mumbai,Hyderabad,BOM → HYD,07:05,85,non-stop,4995
10660,IndiGo,2019-12-06,Mumbai,Hyderabad,BOM → HYD,21:20,90,non-stop,2227

In [33]:
# ft[ft['Source'] == 'Delhi'].head()
ft[ft['Source'] == 'Mumbai'].head()
# ft[ft['Source'] == 'Kolkata'].head()
# ft[ft['Source'] == 'Hyderabad'].head()
# ft[ft['Source'] == 'Cochin'].head()
# ft[ft['Source'] == 'Chennai'].head()
# # ft[ft['Source'] == 'New Delhi'].head()
# ft[ft['Source'] == 'Banglore'].head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Price
14,IndiGo,2019-01-03,Mumbai,Hyderabad,BOM → HYD,16:55,90,non-stop,8853
26,Air India,2019-01-03,Mumbai,Hyderabad,BOM → HYD,13:55,90,non-stop,10082
95,IndiGo,2019-01-03,Mumbai,Hyderabad,BOM → HYD,02:30,90,non-stop,16000
120,Jet Airways,2019-01-03,Mumbai,Hyderabad,BOM → HYD,07:10,85,non-stop,17501
125,IndiGo,2019-01-03,Mumbai,Hyderabad,BOM → HYD,06:20,85,non-stop,17501